export const ONESECOND_INMILLISECONDS = 1000;
export const ONEMINUTE_INSECONDS = 60;
export const ONEHOUR_INMINUTES = 60;
export const ONEDAY_INHOURS = 24;
export const ONEMONTH_INDAYS = 30;
export const ONEYEAR_INMONTHS = 12;
export const ONEDAY_INMILLISECONDS =
  ONESECOND_INMILLISECONDS *
  ONEMINUTE_INSECONDS *
  ONEHOUR_INMINUTES *
  ONEDAY_INHOURS;
