stages:         
  - prepare

image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

before_script:
  - yarn install --frozen-lockfile

eslint:
  stage: prepare
  script:
    - yarn lint

unit-test:
  stage: prepare
  script:
    - yarn test
